export interface Titulo {
    idLote?: string,
    idTitulo?: string,
    idEmpresa?: string,
    idUsuario?: string,

    nomeCredor?: string,
    email?: string,
    tipo?: string,
    numeroDocumento?: string,
    rg?: string,
    telefone?:string,
    cep?:string,
    endereco?:string,
    numero?:string,
    complemento?:string,
    bairro?:string,
    cidade?:string,
    estado?:string,

    bancoId?:number,
    agencia?:string,
    conta?:string,

    siglaEspecie?:string,
    tipoProtesto?:string,
    pracaPagamento?:string,
    dataEmissao?:string,
    vencimento?:string,

    numeroTitulo?:string,
    alinea?:string,
    valorOriginalTitulo?:number,
    valorProtesto?:number,
    endosso?:string,
    favorecido?:string,
    endossante?:string,
    tipoDocumentoEndossante?:string,
    documentoEndossante?:string,    
}